### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Maxbroooooo** [TheOnlyArtz/may#5]
Hi when i start my bot, terminal give me an error:

```node:17364)` UnhandledPromiseRejectionWarning:  @Error:FFMPEG not found
    at Function.selectFfmpegCommand (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:46:13)
    at new FfmpegTranscoder (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:7:37)
    at new MediaTranscoder (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\node_modules\prism-media\src\transcoders\MediaTranscoder.js:10:19)
    at new Prism (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\node_modules\prism-media\src\Prism.js:5:23)
    at new VoiceConnection (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\node_modules\discord.js\src\client\voice\VoiceConnection.js:46:18)
    at Promise (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:63:22)
    at new Promise (<anonymous>)
    at ClientVoiceManager.joinChannel (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:45:12)
    at VoiceChannel.join (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\node_modules\discord.js\src\structures\VoiceChannel.js:130:30)
    at checkGuildVC (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\functions\music\checkGuildVC.js:6:33)
    at Object.module.exports.run (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\commands\play.js:21:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:17364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
with a non-zero exit code.```

can you help me ?

**Comment by gngrchrl** [comment]
1) This project is no longer supported. 
2) You need ffmpeg installed.

**Comment by Maxbroooooo** [comment]
Now, i have this error:
```(node:13528) UnhandledPromiseRejectionWarning: ReferenceError: logger is not defined
    at msg.member.voiceChannel.join.then (C:\Users\Utilisateur\Desktop\BotskytariaV2.0\functions\music\checkGuildVC.js:8:11)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:13528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
with a non-zero exit code.```

**Comment by TheOnlyArtz** [comment]
As @tiehm suggested, this project is no longer maintained and should only be taken as a model and example for future bots.
